name: Continuous Integration Config
on: [push]

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  EXP_TIME: 30000

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package -DskipTests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EXP_TIME: ${{ env.EXP_TIME }}
      - name: Testing echo
        run: echo "${{ secrets.SECRET_KEY }} o a ver qe onda con esto ${{ env.SECRET_KEY }}"
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Tests with Maven
        run: mvn test --batch-mode
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}
          EXP_TIME: ${{ env.EXP_TIME }}