name: Mi Flujo de Trabajo

on:
  push:
    branches:
      - main

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  EXP_TIME: valor_de_expiracion

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar la Aplicación
        run: echo "${{ secrets.SECRET_KEY }} dale que va ${{ env.SECRET_KEY }} x aca tmb ${{ env.EXP_TIME }}"
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EXP_TIME: ${{ env.EXP_TIME }}